APP_NAME=__APP_NAME__
APP_ENV=local
APP_KEY=
APP_DEBUG=false
APP_URL=http://127.0.0.1:8000
APP_TIMEZONE=UTC

LOG_CHANNEL=stack
LOG_LEVEL=info

CACHE_STORE=redis
SESSION_DRIVER=file
QUEUE_CONNECTION=redis

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=

BITRIX24_CLIENT_ID=
BITRIX24_CLIENT_SECRET=
BITRIX24_REDIRECT_URI=__BITRIX24_REDIRECT_URI__
BITRIX24_SCOPE=entity
BITRIX24_REQUEST_TIMEOUT=15
BITRIX24_RETRY_ATTEMPTS=3
BITRIX24_CREDENTIAL_STORE=local_encrypted
